LibU: File system
File system
Overview
The File system module provides a small set of interfaces to do basic file juggling tasks: move, copy an remove.
Functions
int u_copy (const char *src, const char *dst)
Copy a file.
int u_move (const char *src, const char *dst)
Move a file.
int u_remove (const char *file)
Remove a file.
Function Documentation
int u_copy (const char * src, const char * dst)
Copy the file whose path name is src to dst
Parameters:
src source file name
dst destination file name
Return values:
0 on success
~0 on failure
Definition at line 35 of file fs.c.
Referenced by u_move().
int u_move (const char * src, const char * dst)
Move the file whose path name is src to dst
Parameters:
src source file name
dst destination file name
Return values:
0 on success
~0 on failure
Definition at line 79 of file fs.c.
References u_copy(), and u_remove().
int u_remove (const char * file)
Unlink the file whose path name is file
Parameters:
file the file to remove
Return values:
0 on success
~0 on failure
Definition at line 114 of file fs.c.
Referenced by u_move().
←Products
© 2005-2012 - KoanLogic S.r.l. - All rights reserved